### ISSUE TITLE
Instructions on Smarch 

### ISSUE THREAD

**Issue by FAMILIAR-project** [FAMILIAR-project/usampling-exp#1]
/home/samplingfm/scripts/sharpSAT is already available... we have to check whether we need another, more up-to-date information (note: this "issue" applies to other solvers based on sharpSAT) 

also `g++-5` is hard to install since we have 
```
root@7f5d30b96d76:/home# g++ --version
g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

lib-gmp is what?
```
apt-get install lib-gmp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package lib-gmp
```

**Comment by gperroui** [comment]
Hello, 

I updated the README file to make it clearer.  
1. Any g++ above 4.7 should work (the command g++-5 should be present on the system)
2.  it is libgmp-dev (wrong package sorry) on Debian.

**Comment by FAMILIAR-project** [comment]
Thanks a lot! 

I have succeeded to make it work by simply cloning https://github.com/jeho-oh/Kclause_Smarch 
(the binaries of sharpSAT and march_cu are arleady shipped in the repo) 
so the Docker integration is "easy" I would say
