### ISSUE TITLE
smarch + dimacs parsing

### ISSUE THREAD

**Issue by FAMILIAR-project** [FAMILIAR-project/usampling-exp#2]
I implement a quick workaround:
https://github.com/FAMILIAR-project/usampling-exp/blob/master/smarch.py#L36-L37 commit https://github.com/FAMILIAR-project/usampling-exp/commit/e683b5b822b6e8d04e599e22b3a7737cf6661b20 

I'm wondering whether it's OK (in fact I don't get the `split(" ", 4)` why 4? (in the conditional for processing `c`)

**Comment by gperroui** [comment]
I think it is better to put 'continue' than my original pass, SMARCH does not like these 'c ind' comments.  Regarding the split (this is part of the original code) my guess is that it did not expect more elements in these comment lines...
